# Service: This manifest exposes the Django application to the internet or within the cluster.
# A LoadBalancer service type makes it accessible over the internet when running on supported cloud providers.
apiVersion: v1
kind: Service
metadata:
  name: django-app
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000 #port to the django-app image
      nodePort: 30000
  selector:
    app: django-app
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: django-app
        tier: frontend
    spec:
      initContainers:
        - name: init-django
          image: alexun/django-app:latest
          command: ["sh", "-c"]
          args:
            - |
              python manage.py migrate
              python manage.py shell -c "from django.contrib.auth.models import User; User.objects.filter(username='adminuser').exists() or User.objects.create_superuser('adminuser', 'yunqianxu0331@gmail.com', 'M7sTSEc3!')"
      containers:
        - name: django-app
          image: alexun/django-app:latest
          ports:
            - containerPort: 8000
