apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: bTdzVFNFYzMhCg== # Base64 encoded password "M7sTSEc3!"
---
apiVersion: v1
kind: Service
metadata:
  name: django-mysql-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: django-app
    tier: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-mysql-deployment
  labels:
    app: django-app
    tier: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
      tier: mysql
  template:
    metadata:
      labels:
        app: django-app
        tier: mysql
    spec:
      containers:
        - image: alexun/mysql
          name: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
