FROM mysql:latest

# Environment variables
ENV MYSQL_DATABASE=midterm_project_database \
    MYSQL_USER=admin \
    MYSQL_PASSWORD=M7sTSEc3! \
    MYSQL_ROOT_PASSWORD=M7sTSEc3!!

EXPOSE 3306

#docer run -p 3306:3306